apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "a3s-gateway.fullname" . }}
  labels:
    {{- include "a3s-gateway.labels" . | nindent 4 }}
data:
  gateway.hcl: |
    {{- .Values.config | nindent 4 }}
