apiVersion: v1
kind: Service
metadata:
  name: {{ include "a3s-gateway.fullname" . }}
  labels:
    {{- include "a3s-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if .Values.dashboard.enabled }}
    - name: dashboard
      port: {{ .Values.dashboard.port }}
      targetPort: dashboard
      protocol: TCP
    {{- end }}
  selector:
    {{- include "a3s-gateway.selectorLabels" . | nindent 4 }}
